# Generated by Django 4.2.5 on 2023-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Sitio', '0022_alter_animal_ani_anilha_alter_animal_ani_castr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ani_idade',
        ),
    ]
